# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=15, verbose_name='\u7528\u6237\u540d')),
                ('user_passwd', models.CharField(max_length=40, verbose_name='\u5bc6\u7801')),
                ('user_level', models.CharField(choices=[(b'0', '\u666e\u901a\u7528\u6237'), (b'1', '\u540e\u53f0\u7ba1\u7406\u5458'), (b'2', '\u8d85\u7ea7\u7ba1\u7406\u5458')], default=b'0', max_length=2, verbose_name='\u7528\u6237\u6743\u9650\u7b49\u7ea7')),
            ],
            options={
                'db_table': 'userinfo',
                'verbose_name': '\u6ce8\u518c\u7528\u6237\u8868',
                'verbose_name_plural': '\u6ce8\u518c\u7528\u6237\u8868',
            },
        ),
    ]
